name: Halo 5 Match Results
description: Adapter that searches for Halo 5 match results from either a specific matchid, or attempts to find the proper match using other input variables (date, gamertags) 
node_identifier: halo5-match-results
platforms:
  - AWS Lambda
data_sources:
  - name: 343 Industry's Halo Public API
    url: https://developer.haloapi.com/